platform: linux
image_resource:
  type: docker-image
  source: { repository: golang, tag: 1.7-alpine }

inputs:
- name: acbuild-gstore
  path: go/src/github.com/desource/acbuild-gstore-resource

outputs:
- name: out

run:
  path: go/src/github.com/desource/acbuild-gstore-resource/ci/build.sh
